### PR TITLE
Removing oSPARC application entries

### PR DESCRIPTION
**Pull request by ignapas**
oSPARC specific appearances, decorators and fonts were moved here and now are brought back to the oSPARC repo.
Regarding the colors, I am not sure all of them are Qooxdoo related and not only for oSPARC. I only moved the ones under the comment **OSPARC RELATED**. But in any case we can move them to the oSPARC repo progressively as we find they are not at the right place.

Now the meta themes OSparcBlue, Dark, etc are not used by oSPARC.

**Please check version increase is correct, and that new version is released**

### CODE REVIEW

**Comment by odeimaiz** [comment]
Why are we moving them back if this is an osparc specific theming repo?

**Comment by ignapas** [comment]
> Why are we moving them back if this is an osparc specific theming repo?

In my opinion, the stuff related to our application should in the application's repo because:
* It is easier to add modify stuff.
  * We don't have to wait until the updates get merged to master and tagged as a new release in the theme's repo.
  * While developing, we can just modify stuff and refresh the browser.
* Maybe no one uses it, but it should be possible for other people to use the theme in their apps, and in that case our stuff is completely useless for them.
* I think this is the way themes are conceived, to only target Qooxdoo's aliases.

**Comment by odeimaiz** [comment]
I don't recall we agreed on that. I think that the theming should be separated from the code, but you are the one doing the most one the aesthetics side... if you think this will help, go for it 👍

**Comment by ignapas** [comment]
> I don't recall we agreed on that. I think that the theming should be separated from the code, but you are the one doing the most one the aesthetics side... if you think this will help, go for it

well I would say YOU have been doing on more on aesthetics for oSPARC lately! but yes, I am sure it will help..

**Pull request merged**
